insert into clientes (nome, sexo, email, cidade)
VALUES
('João Silva', 'M', 'joao.silva@email.com', 'São Paulo'),
('Maria Oliveira', 'F', 'maria.oliveira@email.com', 'Rio de Janeiro'),
('Pedro Santos', 'M', 'pedro.santos@email.com', 'Belo Horizonte'),
('Ana Costa', 'F', 'ana.costa@email.com', 'Curitiba'),
('Lucas Pereira', 'M', 'lucas.pereira@email.com', 'Porto Alegre'),
('Fernanda Souza', 'F', 'fernanda.souza@email.com', 'Salvador'),
('Carlos Lima', 'M', 'carlos.lima@email.com', 'Fortaleza'),
('Juliana Rocha', 'F', 'juliana.rocha@email.com', 'Recife'),
('Bruno Alves', 'M', 'bruno.alves@email.com', 'Brasília'),
('Patricia Gomes', 'F', 'patricia.gomes@email.com', 'Goiânia'),
('Rafael Martins', 'M', 'rafael.martins@email.com', 'Campinas'),
('Camila Ribeiro', 'F', 'camila.ribeiro@email.com', 'Florianópolis'),
('Diego Fernandes', 'M', 'diego.fernandes@email.com', 'Manaus'),
('Larissa Teixeira', 'F', 'larissa.teixeira@email.com', 'Natal'),
('André Carvalho', 'M', 'andre.carvalho@email.com', 'Vitória'),
('Beatriz Almeida', 'F', 'beatriz.almeida@email.com', 'João Pessoa'),
('Thiago Ribeiro', 'M', 'thiago.ribeiro@email.com', 'Maceió'),
('Sofia Martins', 'F', 'sofia.martins@email.com', 'Aracaju'),
('Gabriel Barbosa', 'M', 'gabriel.barbosa@email.com', 'São Luís'),
('Isabela Fernandes', 'F', 'isabela.fernandes@email.com', 'Teresina'),
('Mateus Costa', 'M', 'mateus.costa@email.com', 'Campo Grande'),
('Valentina Torres', 'F', 'valentina.torres@email.com', 'Cuiabá'),
('Hugo Nascimento', 'M', 'hugo.nascimento@email.com', 'Belém'),
('Renata Lopes', 'F', 'renata.lopes@email.com', 'Palmas'),
('Eduardo Freitas', 'M', 'eduardo.freitas@email.com', 'Uberlândia'),
('Aline Batista', 'F', 'aline.batista@email.com', 'Ribeirão Preto'),
('Marcos Vinicius', 'M', 'marcos.vinicius@email.com', 'Sorocaba'),
('Carolina Duarte', 'F', 'carolina.duarte@email.com', 'Santos'),
('Felipe Araujo', 'M', 'felipe.araujo@email.com', 'Niterói'),
('Daniela Mendes', 'F', 'daniela.mendes@email.com', 'São Bernardo do Campo');


insert into produtos (nome, preco) VALUES
('Notebook Dell', 3500.00),
('Notebook Lenovo', 3200.00),
('Mouse Logitech', 80.00),
('Teclado Mecânico', 250.00),
('Monitor 24 Polegadas', 900.00),
('Monitor 27 Polegadas', 1200.00),
('Headset Gamer', 300.00),
('Webcam HD', 150.00),
('Cadeira Gamer', 950.00),
('Mesa para Computador', 700.00),
('HD Externo 1TB', 400.00),
('SSD 480GB', 350.00),
('SSD 1TB', 600.00),
('Pen Drive 64GB', 60.00),
('Pen Drive 128GB', 90.00),
('Roteador Wi-Fi', 200.00),
('Placa de Vídeo RTX 3060', 2500.00),
('Processador Intel i5', 1200.00),
('Processador Ryzen 5', 1100.00),
('Memória RAM 8GB', 180.00),
('Memória RAM 16GB', 320.00),
('Fonte 500W', 250.00),
('Fonte 750W', 400.00),
('Gabinete Gamer', 300.00),
('Cooler para CPU', 120.00),
('Notebook Gamer', 5500.00),
('Tablet Samsung', 1500.00),
('Smartphone Android', 2000.00),
('Smartphone iOS', 4500.00),
('Smartwatch', 800.00);


insert into pedidos (data, idcliente) VALUES
('2026-01-10', 1),
('2026-01-11', 2),
('2026-01-12', 3),
('2026-01-13', 1),
('2026-01-14', 5),
('2026-01-15', 2),
('2026-01-16', 10),
('2026-01-17', 8);


INSERT INTO pedido_produto (idpedido, idproduto, quantidade) VALUES
(1, 1, 1),
(1, 3, 2),
(2, 4, 1),
(2, 5, 1),
(3, 2, 1),
(3, 6, 2),
(4, 10, 1),
(5, 7, 1),
(6, 8, 2),
(7, 9, 1),
(8, 11, 1);